import {StyledSelectOption} from '../interfaces/interfaces.ts';

export const lineVatRateSimplified: StyledSelectOption[]  = [
  {name: 'AAM', value: '0'},
  {name: '27%', value: '0.2126'},
  {name: '18%', value: '0.1525'},
  {name: '5%', value: '0.0476'},
  {name: '0', value: '0'},
  {name: 'TAM', value: '0'},
];

export const lineVatRateNormal: StyledSelectOption[] = [
  {name: 'AAM', value: '0'},
  {name: '27%', value: '0.27'},
  //{name:"25%", value: "0.25"},
  //{name:"20%", value: "0.20"},
  {name: '18%', value: '0.18'},
  //{name:"12%", value: "0.12"},
  //{name:"7%", value: "0.07"},
  {name: '5%', value: '0.05'},
  {name: '0%', value: '0'},
  {name: 'TAM', value: '0'},
];

export const streetTypes: string[] = [
  'út',
  'utca',
  'útja',
  'allé',
  'alsó rakpart',
  'alsósor',
  'bekötőút',
  'dűlő',
  'fasor',
  'felső rakpart',
  'felsősor',
  'főtér',
  'főút',
  'gát',
  'határ',
  'határsor',
  'határút',
  'ipartelep',
  'kert',
  'kertsor',
  'korzó',
  'környék',
  'körönd',
  'körtér',
  'körút',
  'köz',
  'lakópark',
  'lakótelep',
  'lejtő',
  'lépcső',
  'lépcsősor',
  'liget',
  'major',
  'mélyút',
  'negyed',
  'oldal',
  'országút',
  'park',
  'part',
  'pincesor',
  'puszta',
  'rakpart',
  'sétány',
  'sikátor',
  'sor',
  'sugárút',
  'szállás',
  'szektor',
  'szél',
  'szer',
  'sziget',
  'szőlőhegy',
  'tag',
  'tanya',
  'telep',
  'tér',
  'tető',
  'udvar',
  'üdülőpart',
  'üdülősor',
  'üdülőtelep',
  'vár',
  'várkert',
  'város',
  'villasor',
  'völgy',
  'zug',
];
